@startuml
'https://plantuml.com/class-diagram

class MainMenu {
-Stage stage
-Scene scene
-Parent root
+Label startUpText
+MenuItem addList
+MenuItem loadList
+MenuItem saveList
+FileChooser fileChooser
+continueToTaskList(Actionevent actionevent)
+clicksaveButton(Actionevent actionevent)
+clickloadButton(Actionevent actionevent)
}

@enduml